services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Main LocalStack endpoint (Edge port)
      - "4571:4571" # Optional: Lambda endpoint (or any other specific service)
    environment:
      - SERVICES=s3,dynamodb,sns,sqs,sts
      - AWS_ACCESS_KEY_ID=fake_access_key
      - AWS_SECRET_ACCESS_KEY=fake_secret_key
    volumes:
      - "./localstack_data:/var/lib/localstack" # Persist data locally for localstack
