networks:
  ollama_network:

services:
  ollama:
    build: .
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - ollama_network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_LOG_LEVEL=info
      - OLLAMA_TIMEOUT=30
      - CUDA_VISIBLE_DEVICES="-1"
