# Observability Analysis Configuration
# All settings are optional - defaults will be used if not specified

# Flapping detection settings
flapping:
  flap_window_minutes: 60           # Time window for detecting cycles
  flap_min_cycles: 3                # Minimum cycles to consider flapping
  flap_max_transitions_per_hour: 10 # Transition rate threshold
  flap_cv_threshold: 0.5            # Coefficient of variation threshold
  enable_advanced_flapping: false   # Use advanced pattern detection

# Benign transient detection settings
transient:
  transient_max_duration_seconds: 300.0  # 5 minutes max for transients
  transient_window_seconds: 3600.0       # 1 hour window check
  transient_min_gap_seconds: 1800.0      # 30 minutes between transients
  require_simple_transition: true        # Only alert->recover transitions
  consider_business_hours: true          # Factor in business hours

# Actionable alert settings
actionable:
  actionable_min_duration_seconds: 600.0  # 10 minutes minimum
  actionable_min_ttl_seconds: 120.0       # 2 minutes time-to-live
  human_action_weight: 0.4                # Weight for human action indicators
  business_hours_weight: 0.15             # Weight for business hours

# Business hours configuration (Brazilian timezone)
business_hours:
  start_hour: 9                     # 9 AM
  end_hour: 17                      # 5 PM
  timezone_offset_hours: -3         # UTC-3 (BRT/BRST)
  exclude_weekends: true            # Exclude Sat/Sun
  business_days: [0, 1, 2, 3, 4]   # Monday-Friday

# Trend analysis settings
trend_analysis:
  min_weeks_for_trends: 3           # Minimum weeks needed
  default_lookback_weeks: 8         # Default analysis period
  max_retention_weeks: 12           # Storage retention
  min_trend_significance: 0.3       # Statistical significance threshold
  slope_significance_threshold: 0.01 # Change magnitude threshold
  notable_change_threshold: 20.0     # Percentage change for notifications
  enable_trend_alerts: false        # Automated trend alerting

# Analysis thresholds
thresholds:
  noise_score_high_threshold: 80.0      # High noise threshold
  noise_score_medium_threshold: 60.0    # Medium noise threshold
  self_heal_high_threshold: 0.8         # 80% self-healing rate
  self_heal_low_threshold: 0.2          # 20% self-healing rate
  health_score_a_threshold: 80.0        # Grade A cutoff
  health_score_b_threshold: 70.0        # Grade B cutoff
  health_score_c_threshold: 60.0        # Grade C cutoff
  health_score_d_threshold: 50.0        # Grade D cutoff
  high_confidence_threshold: 0.85       # High confidence recommendations
  medium_confidence_threshold: 0.70     # Medium confidence
  low_confidence_threshold: 0.50       # Low confidence

# Hysteresis and debounce recommendations
hysteresis:
  enable_hysteresis: false               # Enable hysteresis suggestions
  up_threshold_multiplier: 1.05         # 5% higher for alerts
  down_threshold_multiplier: 0.95       # 5% lower for recovery
  default_debounce_seconds: 60.0        # 1 minute default debounce
  max_debounce_seconds: 300.0           # 5 minutes maximum
  enable_debounce_recommendations: true  # Include debounce suggestions

# Global settings
analysis_period_days: 30              # Analysis window
enable_advanced_analysis: true        # Advanced metrics and ML
enable_trend_analysis: true           # Temporal trend analysis
snapshots_dir: "snapshots"           # Snapshot storage directory
enable_snapshot_cleanup: true        # Automatic cleanup of old snapshots
include_recommendations: true        # Include actionable recommendations
max_recommendations_per_type: 10     # Limit recommendations per category